name: publish

on:
  push:    
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@d9f893f837a29f066e3c70080540976b47263721
        with:
          scheme: full
          run: |
            apk add cargo gcc linux-headers musl-dev py3-pip python3 python3-dev rust
            ./make.sh
# deploy to github pages
      - name: deploy documentation
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e
        with:
          branch: gh-pages
          folder: /home/runner/work/programmingWithPython/programmingWithPython/website/
          single-commit: true
